# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae681412303b321270c66238a224545bf9baf108cebb564f560555511b317c13dbf6561ba49f570b8cb5026288ef7f3691461fe76916423a6890d34db024101f

test:
  secret_key_base: b5d655e7ed2bf54e54fea2e6b9709c2ea484bc195c2072d211698834dab7e4ecb6ef784d91660f173969a96e49990083f16fa1419023fbf49e1b12b1c626b8bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
